/* THE NATIONAL FINISHED TAIL, GENERATED BY THE BACKEND'S OWN CODE — not
 * written from a brief.
 *
 * `src.match_archive.tail.assemble(date="20260927", back=8)` on the
 * backend branch `match-archive` (2026-09-27), in process, over a
 * throwaway SQLite live plane seeded exactly as that branch's
 * tests/test_match_archive.py `_seed_three` seeds it: England 2-3 Spain
 * (UNL, 2026-09-26) finalized from the RECORDED ESPN summary with a T-10
 * capture, and one UNL fixture kicked off but not finalized. The ESPN
 * fallback read the RECORDED UNL scoreboard for 2026-09-26
 * (tests/fixtures/espn/scoreboard_uefa.nations_20260926.json.gz); CNL's
 * fallback read an empty day; AFCON's fallback was made to fail with a
 * 503, so its column carries the backend's own failure sentence.
 *
 * So the three columns hold the three states a tail must keep apart:
 * UNL read (ten finished — one from the archive, nine from ESPN, marked),
 * CNL read and none finished, AFCON read and failed. Nothing below was
 * edited by hand. */
export const NATIONS_REVIEW = {
 "generated_at": "2026-09-27T12:00:00+00:00",
 "date": "20260927",
 "back": 8,
 "window": {
  "from": "20260919",
  "to": "20260927"
 },
 "store": {
  "backend": "match_archive",
  "writable": true,
  "note": "national finished matches are read from the match archive; ESPN only where it has nothing yet, marked per row"
 },
 "lead_band_ladder": [],
 "leagues": {
  "unl": {
   "finished": 10,
   "captured": 1,
   "reconstructed": 0,
   "unavailable": 9,
   "error": null,
   "kind": "national",
   "captured_by_lead_band": {
    "t10": 1
   },
   "corrected": 0,
   "source": "archive+espn_fallback",
   "source_note": "read from ESPN's scoreboard: the match archive has not finalized this match yet",
   "awaiting_finalize": 1
  },
  "cnl": {
   "finished": 0,
   "captured": 0,
   "reconstructed": 0,
   "unavailable": 0,
   "error": null,
   "kind": "national",
   "captured_by_lead_band": {},
   "corrected": 0,
   "source": "espn_fallback",
   "source_note": "the match archive holds nothing for this competition yet",
   "awaiting_finalize": 0
  },
  "afcon": {
   "finished": 0,
   "captured": 0,
   "reconstructed": 0,
   "unavailable": 0,
   "error": "the ESPN scoreboard answered 503, the provider's own service failed",
   "kind": "national",
   "captured_by_lead_band": {},
   "corrected": 0,
   "source": "espn_fallback",
   "source_note": "the match archive holds nothing for this competition yet",
   "awaiting_finalize": 0
  }
 },
 "finished": [
  {
   "league": "unl",
   "espn": "uefa.nations",
   "kind": "national",
   "event_id": "401861062",
   "competition_id": "401861062",
   "kickoff": "2026-09-26T18:45Z",
   "home": "Albania",
   "away": "Belarus",
   "status_detail": "FT",
   "result": {
    "home": 2,
    "away": 0,
    "winner": "home",
    "source": "espn_scoreboard"
   },
   "pre_kickoff": {
    "origin": "unavailable",
    "origin_label": "NOT AVAILABLE",
    "origin_note": "read from ESPN's scoreboard: the match archive has not finalized this match yet",
    "unavailable_reason": "archive_not_finalized_yet",
    "captured_at": null,
    "captured_seconds_before_kickoff": null,
    "captured_lead_band": null,
    "captured_lead_band_means": null,
    "board_date": null,
    "superseded": [],
    "corrections": 0,
    "reconstructed_from": null,
    "store_read": "ok",
    "store_read_error": null,
    "state": null
   },
   "shot_state": {
    "at_20": null,
    "before_first_goal": null,
    "full_time": null,
    "first_goal_minute": null,
    "error": "the match archive keeps goal and red-card minutes and the team totals, not a shot-by-shot tape, so no checkpoint can be read"
   },
   "fit": {
    "favourite_won": null,
    "favourite_won_reason": "no_pre_kickoff_favourite",
    "confirmed_at_20": null,
    "confirm_reason": "no_pre_kickoff_favourite",
    "confirm_rule": "tilt_fav_and_on_target_lead",
    "confirm_note": "EXPLORATORY — NOT VALIDATED, NOT PREREGISTERED, NO LEDGER ROW. The confirm rule is: the favourite leads the card's threat tilt (band patterns.TILT_THREAT) AND leads the on-target count. The band is the card's own; the on-target leg adds no tuned number. It was written after looking at three fixtures and it describes a row — it forecasts nothing.",
    "checkpoint_minute": 20
   },
   "column": "unl",
   "columns": [
    "unl"
   ]
  },
  {
   "league": "unl",
   "espn": "uefa.nations",
   "kind": "national",
   "event_id": "401861063",
   "competition_id": "401861063",
   "kickoff": "2026-09-26T18:45Z",
   "home": "Czechia",
   "away": "Croatia",
   "status_detail": "FT",
   "result": {
    "home": 1,
    "away": 2,
    "winner": "away",
    "source": "espn_scoreboard"
   },
   "pre_kickoff": {
    "origin": "unavailable",
    "origin_label": "NOT AVAILABLE",
    "origin_note": "read from ESPN's scoreboard: the match archive has not finalized this match yet",
    "unavailable_reason": "archive_not_finalized_yet",
    "captured_at": null,
    "captured_seconds_before_kickoff": null,
    "captured_lead_band": null,
    "captured_lead_band_means": null,
    "board_date": null,
    "superseded": [],
    "corrections": 0,
    "reconstructed_from": null,
    "store_read": "ok",
    "store_read_error": null,
    "state": null
   },
   "shot_state": {
    "at_20": null,
    "before_first_goal": null,
    "full_time": null,
    "first_goal_minute": null,
    "error": "the match archive keeps goal and red-card minutes and the team totals, not a shot-by-shot tape, so no checkpoint can be read"
   },
   "fit": {
    "favourite_won": null,
    "favourite_won_reason": "no_pre_kickoff_favourite",
    "confirmed_at_20": null,
    "confirm_reason": "no_pre_kickoff_favourite",
    "confirm_rule": "tilt_fav_and_on_target_lead",
    "confirm_note": "EXPLORATORY — NOT VALIDATED, NOT PREREGISTERED, NO LEDGER ROW. The confirm rule is: the favourite leads the card's threat tilt (band patterns.TILT_THREAT) AND leads the on-target count. The band is the card's own; the on-target leg adds no tuned number. It was written after looking at three fixtures and it describes a row — it forecasts nothing.",
    "checkpoint_minute": 20
   },
   "column": "unl",
   "columns": [
    "unl"
   ]
  },
  {
   "league": "unl",
   "espn": "uefa.nations",
   "kind": "national",
   "event_id": "401861065",
   "competition_id": "401861065",
   "kickoff": "2026-09-26T18:45Z",
   "home": "North Macedonia",
   "away": "Switzerland",
   "status_detail": "FT",
   "result": {
    "home": 0,
    "away": 3,
    "winner": "away",
    "source": "espn_scoreboard"
   },
   "pre_kickoff": {
    "origin": "unavailable",
    "origin_label": "NOT AVAILABLE",
    "origin_note": "read from ESPN's scoreboard: the match archive has not finalized this match yet",
    "unavailable_reason": "archive_not_finalized_yet",
    "captured_at": null,
    "captured_seconds_before_kickoff": null,
    "captured_lead_band": null,
    "captured_lead_band_means": null,
    "board_date": null,
    "superseded": [],
    "corrections": 0,
    "reconstructed_from": null,
    "store_read": "ok",
    "store_read_error": null,
    "state": null
   },
   "shot_state": {
    "at_20": null,
    "before_first_goal": null,
    "full_time": null,
    "first_goal_minute": null,
    "error": "the match archive keeps goal and red-card minutes and the team totals, not a shot-by-shot tape, so no checkpoint can be read"
   },
   "fit": {
    "favourite_won": null,
    "favourite_won_reason": "no_pre_kickoff_favourite",
    "confirmed_at_20": null,
    "confirm_reason": "no_pre_kickoff_favourite",
    "confirm_rule": "tilt_fav_and_on_target_lead",
    "confirm_note": "EXPLORATORY — NOT VALIDATED, NOT PREREGISTERED, NO LEDGER ROW. The confirm rule is: the favourite leads the card's threat tilt (band patterns.TILT_THREAT) AND leads the on-target count. The band is the card's own; the on-target leg adds no tuned number. It was written after looking at three fixtures and it describes a row — it forecasts nothing.",
    "checkpoint_minute": 20
   },
   "column": "unl",
   "columns": [
    "unl"
   ]
  },
  {
   "league": "unl",
   "espn": "uefa.nations",
   "kind": "national",
   "event_id": "401861064",
   "competition_id": "401861064",
   "kickoff": "2026-09-26T18:45Z",
   "home": "Slovakia",
   "away": "Moldova",
   "status_detail": "FT",
   "result": {
    "home": 2,
    "away": 0,
    "winner": "home",
    "source": "espn_scoreboard"
   },
   "pre_kickoff": {
    "origin": "unavailable",
    "origin_label": "NOT AVAILABLE",
    "origin_note": "read from ESPN's scoreboard: the match archive has not finalized this match yet",
    "unavailable_reason": "archive_not_finalized_yet",
    "captured_at": null,
    "captured_seconds_before_kickoff": null,
    "captured_lead_band": null,
    "captured_lead_band_means": null,
    "board_date": null,
    "superseded": [],
    "corrections": 0,
    "reconstructed_from": null,
    "store_read": "ok",
    "store_read_error": null,
    "state": null
   },
   "shot_state": {
    "at_20": null,
    "before_first_goal": null,
    "full_time": null,
    "first_goal_minute": null,
    "error": "the match archive keeps goal and red-card minutes and the team totals, not a shot-by-shot tape, so no checkpoint can be read"
   },
   "fit": {
    "favourite_won": null,
    "favourite_won_reason": "no_pre_kickoff_favourite",
    "confirmed_at_20": null,
    "confirm_reason": "no_pre_kickoff_favourite",
    "confirm_rule": "tilt_fav_and_on_target_lead",
    "confirm_note": "EXPLORATORY — NOT VALIDATED, NOT PREREGISTERED, NO LEDGER ROW. The confirm rule is: the favourite leads the card's threat tilt (band patterns.TILT_THREAT) AND leads the on-target count. The band is the card's own; the on-target leg adds no tuned number. It was written after looking at three fixtures and it describes a row — it forecasts nothing.",
    "checkpoint_minute": 20
   },
   "column": "unl",
   "columns": [
    "unl"
   ]
  },
  {
   "league": "unl",
   "espn": "uefa.nations",
   "kind": "national",
   "event_id": "401861066",
   "competition_id": "401861066",
   "kickoff": "2026-09-26T18:45:00+00:00",
   "home": "England",
   "away": "Spain",
   "status_detail": "FT",
   "result": {
    "home": 2,
    "away": 3,
    "winner": "away",
    "result_90": "away",
    "extra_time": false,
    "pens": null,
    "source": "match_archive"
   },
   "pre_kickoff": {
    "captured_at": "2026-09-26T12:00:00+00:00",
    "captured_seconds_before_kickoff": 24300,
    "captured_lead_band": null,
    "captured_lead_band_means": null,
    "board_date": null,
    "superseded": [],
    "corrections": 0,
    "reconstructed_from": null,
    "store_read": "ok",
    "store_read_error": null,
    "origin": "captured",
    "origin_label": "CAPTURED",
    "origin_note": "frozen by the match archive at T10, before kickoff — this is what the board said",
    "archive_rung": "t10",
    "unavailable_reason": null,
    "state": {
     "league": "unl",
     "home": "England",
     "away": "Spain",
     "resolution": {},
     "kickoff": "2026-09-26T18:45:00+00:00",
     "event_id": "401861066",
     "cross_league": false,
     "current_only": null,
     "fav_side": "away",
     "fav_source": "field",
     "favourite": "Spain",
     "field": {
      "axes": {
       "atk": {
        "fav": {
         "below_floor": true,
         "half_width_95": 0.16659803248953534,
         "rank": 1,
         "tier": 1,
         "value": 1.3097998676896028
        },
        "opp": {
         "below_floor": true,
         "half_width_95": 0.22416482775882512,
         "rank": 6,
         "tier": 1,
         "value": 0.8915172004617833
        },
        "tier_gap": 0
       },
       "def": {
        "fav": {
         "below_floor": true,
         "half_width_95": 0.4702019687795417,
         "rank": 1,
         "tier": 1,
         "value": 1.0503873543165414
        },
        "opp": {
         "below_floor": true,
         "half_width_95": 0.47189269904626646,
         "rank": 2,
         "tier": 1,
         "value": 0.9790059491538934
        },
        "tier_gap": 0
       },
       "ovr": {
        "fav": {
         "below_floor": false,
         "half_width_95": 35.06052871202671,
         "rank": 1,
         "tier": 1,
         "value": 2050.805034380569
        },
        "opp": {
         "below_floor": false,
         "half_width_95": 42.245759915650325,
         "rank": 3,
         "tier": 1,
         "value": 1937.2129193198243
        },
        "tier_gap": 0
       }
      },
      "competition": "unl",
      "size": 54
     },
     "field_partial": false,
     "gdg_gap": null,
     "gp_current": {
      "away": 0,
      "home": 0,
      "min": 0
     },
     "headline": {
      "favourite_side": "away",
      "label": "ELO GAP",
      "unit": "Elo points",
      "value": 48.6
     },
     "national": {
      "fixture_source": "espn",
      "group": "Group A3",
      "leg": null,
      "neutral": false,
      "stage": "group-stage",
      "stage_kind": "group",
      "venue_country": "England"
     },
     "opponent": "England",
     "own_gdg": {
      "basis": "each team's own goal difference per game in THIS competition's current group, differenced. Two groups of different strength are not one scale, and a handful of games is a handful of games; the field above is the comparison, this is a record.",
      "diff": null
     },
     "ppg_gap": null,
     "rank_gap": null,
     "ranks": {
      "fav": 1,
      "opp": 3
     },
     "rated_in": {
      "away": "unl",
      "home": "unl"
     },
     "rates": {
      "ga": [
       null,
       null
      ],
      "gdg": [
       null,
       null
      ],
      "gf": [
       null,
       null
      ],
      "ppg": [
       null,
       null
      ]
     },
     "refused": false,
     "shape": "HOLLOW",
     "src": "current",
     "tier_gaps": {
      "atk": 0,
      "def": 0,
      "ovr": 0
     },
     "tiers": {
      "atk": [
       1,
       1
      ],
      "def": [
       1,
       1
      ],
      "ovr": [
       1,
       1
      ]
     },
     "venue_class": {
      "class": "TRUE_HOME",
      "home_side": "home"
     },
     "weights": null,
     "kalshi": {
      "event_ticker": "KXUEFANLGAME-26SEP26ENGESP",
      "ticker": "KXUEFANLGAME-26SEP26ENGESP-ESP",
      "ask_c": 42,
      "bid_c": 41,
      "spread_c": 1,
      "ask_size": 1992,
      "bid_size": 555,
      "flags": [
       "CAPTURED"
      ]
     }
    }
   },
   "shot_state": {
    "at_20": null,
    "before_first_goal": null,
    "full_time": null,
    "first_goal_minute": 2,
    "error": "the match archive keeps goal and red-card minutes and the team totals, not a shot-by-shot tape, so no checkpoint can be read"
   },
   "fit": {
    "favourite_won": true,
    "favourite_won_reason": "winner=away fav_side=away",
    "confirmed_at_20": null,
    "confirm_reason": "no_shot_state",
    "confirm_rule": "tilt_fav_and_on_target_lead",
    "confirm_note": "EXPLORATORY — NOT VALIDATED, NOT PREREGISTERED, NO LEDGER ROW. The confirm rule is: the favourite leads the card's threat tilt (band patterns.TILT_THREAT) AND leads the on-target count. The band is the card's own; the on-target leg adds no tuned number. It was written after looking at three fixtures and it describes a row — it forecasts nothing.",
    "checkpoint_minute": 20
   },
   "column": "unl",
   "columns": [
    "unl"
   ]
  },
  {
   "league": "unl",
   "espn": "uefa.nations",
   "kind": "national",
   "event_id": "401861061",
   "competition_id": "401861061",
   "kickoff": "2026-09-26T16:00Z",
   "home": "Bulgaria",
   "away": "Luxembourg",
   "status_detail": "FT",
   "result": {
    "home": 1,
    "away": 2,
    "winner": "away",
    "source": "espn_scoreboard"
   },
   "pre_kickoff": {
    "origin": "unavailable",
    "origin_label": "NOT AVAILABLE",
    "origin_note": "read from ESPN's scoreboard: the match archive has not finalized this match yet",
    "unavailable_reason": "archive_not_finalized_yet",
    "captured_at": null,
    "captured_seconds_before_kickoff": null,
    "captured_lead_band": null,
    "captured_lead_band_means": null,
    "board_date": null,
    "superseded": [],
    "corrections": 0,
    "reconstructed_from": null,
    "store_read": "ok",
    "store_read_error": null,
    "state": null
   },
   "shot_state": {
    "at_20": null,
    "before_first_goal": null,
    "full_time": null,
    "first_goal_minute": null,
    "error": "the match archive keeps goal and red-card minutes and the team totals, not a shot-by-shot tape, so no checkpoint can be read"
   },
   "fit": {
    "favourite_won": null,
    "favourite_won_reason": "no_pre_kickoff_favourite",
    "confirmed_at_20": null,
    "confirm_reason": "no_pre_kickoff_favourite",
    "confirm_rule": "tilt_fav_and_on_target_lead",
    "confirm_note": "EXPLORATORY — NOT VALIDATED, NOT PREREGISTERED, NO LEDGER ROW. The confirm rule is: the favourite leads the card's threat tilt (band patterns.TILT_THREAT) AND leads the on-target count. The band is the card's own; the on-target leg adds no tuned number. It was written after looking at three fixtures and it describes a row — it forecasts nothing.",
    "checkpoint_minute": 20
   },
   "column": "unl",
   "columns": [
    "unl"
   ]
  },
  {
   "league": "unl",
   "espn": "uefa.nations",
   "kind": "national",
   "event_id": "401861060",
   "competition_id": "401861060",
   "kickoff": "2026-09-26T16:00Z",
   "home": "Faroe Islands",
   "away": "Kazakhstan",
   "status_detail": "FT",
   "result": {
    "home": 1,
    "away": 1,
    "winner": "draw",
    "source": "espn_scoreboard"
   },
   "pre_kickoff": {
    "origin": "unavailable",
    "origin_label": "NOT AVAILABLE",
    "origin_note": "read from ESPN's scoreboard: the match archive has not finalized this match yet",
    "unavailable_reason": "archive_not_finalized_yet",
    "captured_at": null,
    "captured_seconds_before_kickoff": null,
    "captured_lead_band": null,
    "captured_lead_band_means": null,
    "board_date": null,
    "superseded": [],
    "corrections": 0,
    "reconstructed_from": null,
    "store_read": "ok",
    "store_read_error": null,
    "state": null
   },
   "shot_state": {
    "at_20": null,
    "before_first_goal": null,
    "full_time": null,
    "first_goal_minute": null,
    "error": "the match archive keeps goal and red-card minutes and the team totals, not a shot-by-shot tape, so no checkpoint can be read"
   },
   "fit": {
    "favourite_won": null,
    "favourite_won_reason": "no_pre_kickoff_favourite",
    "confirmed_at_20": null,
    "confirm_reason": "no_pre_kickoff_favourite",
    "confirm_rule": "tilt_fav_and_on_target_lead",
    "confirm_note": "EXPLORATORY — NOT VALIDATED, NOT PREREGISTERED, NO LEDGER ROW. The confirm rule is: the favourite leads the card's threat tilt (band patterns.TILT_THREAT) AND leads the on-target count. The band is the card's own; the on-target leg adds no tuned number. It was written after looking at three fixtures and it describes a row — it forecasts nothing.",
    "checkpoint_minute": 20
   },
   "column": "unl",
   "columns": [
    "unl"
   ]
  },
  {
   "league": "unl",
   "espn": "uefa.nations",
   "kind": "national",
   "event_id": "401861058",
   "competition_id": "401861058",
   "kickoff": "2026-09-26T16:00Z",
   "home": "Iceland",
   "away": "Estonia",
   "status_detail": "FT",
   "result": {
    "home": 1,
    "away": 1,
    "winner": "draw",
    "source": "espn_scoreboard"
   },
   "pre_kickoff": {
    "origin": "unavailable",
    "origin_label": "NOT AVAILABLE",
    "origin_note": "read from ESPN's scoreboard: the match archive has not finalized this match yet",
    "unavailable_reason": "archive_not_finalized_yet",
    "captured_at": null,
    "captured_seconds_before_kickoff": null,
    "captured_lead_band": null,
    "captured_lead_band_means": null,
    "board_date": null,
    "superseded": [],
    "corrections": 0,
    "reconstructed_from": null,
    "store_read": "ok",
    "store_read_error": null,
    "state": null
   },
   "shot_state": {
    "at_20": null,
    "before_first_goal": null,
    "full_time": null,
    "first_goal_minute": null,
    "error": "the match archive keeps goal and red-card minutes and the team totals, not a shot-by-shot tape, so no checkpoint can be read"
   },
   "fit": {
    "favourite_won": null,
    "favourite_won_reason": "no_pre_kickoff_favourite",
    "confirmed_at_20": null,
    "confirm_reason": "no_pre_kickoff_favourite",
    "confirm_rule": "tilt_fav_and_on_target_lead",
    "confirm_note": "EXPLORATORY — NOT VALIDATED, NOT PREREGISTERED, NO LEDGER ROW. The confirm rule is: the favourite leads the card's threat tilt (band patterns.TILT_THREAT) AND leads the on-target count. The band is the card's own; the on-target leg adds no tuned number. It was written after looking at three fixtures and it describes a row — it forecasts nothing.",
    "checkpoint_minute": 20
   },
   "column": "unl",
   "columns": [
    "unl"
   ]
  },
  {
   "league": "unl",
   "espn": "uefa.nations",
   "kind": "national",
   "event_id": "401861059",
   "competition_id": "401861059",
   "kickoff": "2026-09-26T16:00Z",
   "home": "San Marino",
   "away": "Finland",
   "status_detail": "FT",
   "result": {
    "home": 0,
    "away": 7,
    "winner": "away",
    "source": "espn_scoreboard"
   },
   "pre_kickoff": {
    "origin": "unavailable",
    "origin_label": "NOT AVAILABLE",
    "origin_note": "read from ESPN's scoreboard: the match archive has not finalized this match yet",
    "unavailable_reason": "archive_not_finalized_yet",
    "captured_at": null,
    "captured_seconds_before_kickoff": null,
    "captured_lead_band": null,
    "captured_lead_band_means": null,
    "board_date": null,
    "superseded": [],
    "corrections": 0,
    "reconstructed_from": null,
    "store_read": "ok",
    "store_read_error": null,
    "state": null
   },
   "shot_state": {
    "at_20": null,
    "before_first_goal": null,
    "full_time": null,
    "first_goal_minute": null,
    "error": "the match archive keeps goal and red-card minutes and the team totals, not a shot-by-shot tape, so no checkpoint can be read"
   },
   "fit": {
    "favourite_won": null,
    "favourite_won_reason": "no_pre_kickoff_favourite",
    "confirmed_at_20": null,
    "confirm_reason": "no_pre_kickoff_favourite",
    "confirm_rule": "tilt_fav_and_on_target_lead",
    "confirm_note": "EXPLORATORY — NOT VALIDATED, NOT PREREGISTERED, NO LEDGER ROW. The confirm rule is: the favourite leads the card's threat tilt (band patterns.TILT_THREAT) AND leads the on-target count. The band is the card's own; the on-target leg adds no tuned number. It was written after looking at three fixtures and it describes a row — it forecasts nothing.",
    "checkpoint_minute": 20
   },
   "column": "unl",
   "columns": [
    "unl"
   ]
  },
  {
   "league": "unl",
   "espn": "uefa.nations",
   "kind": "national",
   "event_id": "401861057",
   "competition_id": "401861057",
   "kickoff": "2026-09-26T13:00Z",
   "home": "Slovenia",
   "away": "Scotland",
   "status_detail": "FT",
   "result": {
    "home": 0,
    "away": 0,
    "winner": "draw",
    "source": "espn_scoreboard"
   },
   "pre_kickoff": {
    "origin": "unavailable",
    "origin_label": "NOT AVAILABLE",
    "origin_note": "read from ESPN's scoreboard: the match archive has not finalized this match yet",
    "unavailable_reason": "archive_not_finalized_yet",
    "captured_at": null,
    "captured_seconds_before_kickoff": null,
    "captured_lead_band": null,
    "captured_lead_band_means": null,
    "board_date": null,
    "superseded": [],
    "corrections": 0,
    "reconstructed_from": null,
    "store_read": "ok",
    "store_read_error": null,
    "state": null
   },
   "shot_state": {
    "at_20": null,
    "before_first_goal": null,
    "full_time": null,
    "first_goal_minute": null,
    "error": "the match archive keeps goal and red-card minutes and the team totals, not a shot-by-shot tape, so no checkpoint can be read"
   },
   "fit": {
    "favourite_won": null,
    "favourite_won_reason": "no_pre_kickoff_favourite",
    "confirmed_at_20": null,
    "confirm_reason": "no_pre_kickoff_favourite",
    "confirm_rule": "tilt_fav_and_on_target_lead",
    "confirm_note": "EXPLORATORY — NOT VALIDATED, NOT PREREGISTERED, NO LEDGER ROW. The confirm rule is: the favourite leads the card's threat tilt (band patterns.TILT_THREAT) AND leads the on-target count. The band is the card's own; the on-target leg adds no tuned number. It was written after looking at three fixtures and it describes a row — it forecasts nothing.",
    "checkpoint_minute": 20
   },
   "column": "unl",
   "columns": [
    "unl"
   ]
  }
 ],
 "refusals": [],
 "folded": {}
} as const;
